name: CI

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn ci

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          start: yarn server, yarn start
          wait-on: http://localhost:4000, http://localhost:3000

      - name: Jest/RTL Test
        run: yarn test --watchAll=false
