name: CI

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn ci

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Cypress Test
        uses: cypress-io/github-action@v2
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_CATEGORIES_URL: ${{ secrets.REACT_APP_CATEGORIES_URL }}
          REACT_APP_ORDERS_URL: ${{ secrets.REACT_APP_ORDERS_URL }}
          REACT_APP_USERS_URL: ${{ secrets.REACT_APP_USERS_URL }}
          REACT_APP_WORKSHOPS_LIMIT: ${{ secrets.REACT_APP_WORKSHOPS_LIMIT }}
          REACT_APP_WORKSHOPS_URL: ${{ secrets.REACT_APP_WORKSHOPS_URL }}
        with:
          start: yarn server, doppler run -t ${{ secrets.DOPPLER_TOKEN }} -- vercel dev
          wait-on: http://localhost:4000, http://localhost:3000

      - name: Jest/RTL Test
        run: yarn test --watchAll=false
