name: CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: yarn
      
      - name: Cypress Test
        run: yarn cy
        
      - name: Jest/RTL Test
        run: yarn test --watchAll=false
